---
# http://module-build.sourceforge.net/META-spec.html
name:         Carp-Indeed
version:      0.04
version_from: Indeed.pm
author:
  - Adriano Ferreira <ferreira@cpan.org>
license: perl
installdirs:  site
requires:
    Carp:                          0
recommends:
    Test::Pod:                     1.18

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
